import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:instagram_clone/core/theme/app_theme.dart';
import 'package:instagram_clone/features/profile/presentation/providers/profile_provider.dart';
import 'package:instagram_clone/features/stories/data/models/story_model.dart';
import 'package:instagram_clone/features/stories/presentation/providers/story_provider.dart';
import 'package:instagram_clone/shared/widgets/loading_widget.dart';

class CreateStoryScreen extends ConsumerStatefulWidget {
  const CreateStoryScreen({super.key});

  @override
  ConsumerState<CreateStoryScreen> createState() => _CreateStoryScreenState();
}

class _CreateStoryScreenState extends ConsumerState<CreateStoryScreen> {
  XFile? _selectedImage;
  XFile? _selectedVideo;
  bool _isImage = true;
  bool _isUploading = false;
  final TextEditingController _captionController = TextEditingController();
  final TextEditingController _locationController = TextEditingController();
  final TextEditingController _hashtagsController = TextEditingController();

  @override
  void dispose() {
    _captionController.dispose();
    _locationController.dispose();
    _hashtagsController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    try {
      final pickedFile = await ImagePicker().pickImage(
        source: ImageSource.gallery,
        maxWidth: 1080,
        maxHeight: 1920,
        imageQuality: 80,
      );

      if (pickedFile != null) {
        setState(() {
          _selectedImage = pickedFile;
          _selectedVideo = null;
          _isImage = true;
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to pick image: $e')),
      );
    }
  }

  Future<void> _pickVideo() async {
    try {
      final pickedFile = await ImagePicker().pickVideo(
        source: ImageSource.gallery,
        maxDuration: const Duration(seconds: 15),
      );

      if (pickedFile != null) {
        setState(() {
          _selectedVideo = pickedFile;
          _selectedImage = null;
          _isImage = false;
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to pick video: $e')),
      );
    }
  }

  Future<void> _takePhoto() async {
    try {
      final pickedFile = await ImagePicker().pickImage(
        source: ImageSource.camera,
        maxWidth: 1080,
        maxHeight: 1920,
        imageQuality: 80,
      );

      if (pickedFile != null) {
        setState(() {
          _selectedImage = pickedFile;
          _selectedVideo = null;
          _isImage = true;
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to take photo: $e')),
      );
    }
  }

  Future<void> _createStory() async {
    if (_selectedImage == null && _selectedVideo == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select an image or video')),
      );
      return;
    }

    setState(() {
      _isUploading = true;
    });

    try {
      // Get current user profile
      final profile = await ref.read(currentUserProfileProvider.future);
      if (profile == null) {
        throw Exception('User profile not found');
      }

      // Upload media to Supabase Storage
      String imageUrl = '';
      String? videoUrl;

      if (_selectedImage != null) {
        imageUrl = await _uploadImage();
      }

      if (_selectedVideo != null) {
        videoUrl = await _uploadVideo();
      }

      // Parse hashtags
      final hashtags = _parseHashtags(_hashtagsController.text);

      final story = StoryModel(
        id: '', // Will be generated by Supabase
        userId: profile.id,
        username: profile.username,
        userAvatar: profile.avatarUrl,
        imageUrl: imageUrl,
        videoUrl: videoUrl,
        createdAt: DateTime.now(),
        expiresAt: DateTime.now().add(const Duration(hours: 24)),
        viewers: [],
        isVideo: !_isImage,
        caption: _captionController.text.isEmpty ? null : _captionController.text,
        location: _locationController.text.isEmpty ? null : _locationController.text,
        hashtags: hashtags.isEmpty ? null : hashtags,
      );

      await ref.read(storyRepositoryProvider).createStory(story);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Story created successfully!')),
        );
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create story: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isUploading = false;
        });
      }
    }
  }

  Future<String> _uploadImage() async {
    // TODO: Implement image upload to Supabase Storage
    return 'https://example.com/stories/${_selectedImage?.name}';
  }

  Future<String> _uploadVideo() async {
    // TODO: Implement video upload to Supabase Storage
    return 'https://example.com/stories/${_selectedVideo?.name}';
  }

  List<String> _parseHashtags(String text) {
    final regex = RegExp(r'#(\w+)');
    return regex.allMatches(text).map((match) => match.group(1)!).toList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Story'),
        actions: [
          TextButton(
            onPressed: _isUploading ? null : _createStory,
            child: _isUploading
                ? const LoadingWidget(size: 20)
                : const Text(
                    'Share',
                    style: TextStyle(
                      color: AppTheme.primaryColor,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Media Selection
              _buildMediaSelection(),
              const SizedBox(height: 20),

              // Caption
              TextField(
                controller: _captionController,
                decoration: InputDecoration(
                  hintText: 'Add a caption...',
                  border: InputBorder.none,
                  hintStyle: const TextStyle(color: Colors.grey),
                ),
                maxLines: 3,
              ),
              const SizedBox(height: 16),

              // Location
              TextField(
                controller: _locationController,
                decoration: InputDecoration(
                  hintText: 'Add location',
                  prefixIcon: const Icon(Icons.location_on_outlined),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Hashtags
              TextField(
                controller: _hashtagsController,
                decoration: InputDecoration(
                  hintText: 'Add hashtags (separated by spaces)',
                  prefixIcon: const Icon(Icons.tag),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildMediaSelection() {
    if (_selectedImage == null && _selectedVideo == null) {
      return Column(
        children: [
          // Camera button
          GestureDetector(
            onTap: _takePhoto,
            child: Container(
              height: 200,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey, width: 1),
                borderRadius: BorderRadius.circular(8),
              ),
              child: const Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.add_a_photo_outlined, size: 40, color: Colors.grey),
                    SizedBox(height: 8),
                    Text(
                      'Take Photo',
                      style: TextStyle(color: Colors.grey),
                    ),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),
          
          // Gallery options
          Row(
            children: [
              Expanded(
                child: GestureDetector(
                  onTap: _pickImage,
                  child: Container(
                    height: 100,
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey, width: 1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.image_outlined, size: 30, color: Colors.grey),
                          SizedBox(height: 4),
                          Text(
                            'Gallery',
                            style: TextStyle(color: Colors.grey, fontSize: 12),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: GestureDetector(
                  onTap: _pickVideo,
                  child: Container(
                    height: 100,
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey, width: 1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.videocam_outlined, size: 30, color: Colors.grey),
                          SizedBox(height: 4),
                          Text(
                            'Video',
                            style: TextStyle(color: Colors.grey, fontSize: 12),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(
          height: 400,
          child: _isImage
              ? Image.file(
                  File(_selectedImage!.path),
                  fit: BoxFit.cover,
                  width: double.infinity,
                )
              : const Center(
                  child: Icon(
                    Icons.videocam_outlined,
                    size: 60,
                    color: Colors.grey,
                  ),
                ),
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            Expanded(
              child: OutlinedButton.icon(
                onPressed: _pickImage,
                icon: const Icon(Icons.image_outlined, size: 16),
                label: const Text('Change Image'),
              ),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: OutlinedButton.icon(
                onPressed: _pickVideo,
                icon: const Icon(Icons.videocam_outlined, size: 16),
                label: const Text('Change Video'),
              ),
            ),
            const SizedBox(width: 8),
            OutlinedButton.icon(
              onPressed: () {
                setState(() {
                  _selectedImage = null;
                  _selectedVideo = null;
                });
              },
              icon: const Icon(Icons.delete_outline, size: 16),
              label: const Text('Remove'),
            ),
          ],
        ),
      ],
    );
  }
}
